package AdditionApp;


/**
* AdditionApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Friday, 18 October, 2019 3:18:38 AM IST
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
